PROGRAM EXE4;

TYPE
  PILHA = RECORD
    OBJ: ARRAY[1..100] OF STRING;
    N: INTEGER;
  END;

PROCEDURE INIT(VAR X: PILHA);
BEGIN
  X.N := 0;
END;

PROCEDURE PUSH(VAR X: PILHA; Y: STRING);
BEGIN
  X.N := X.N + 1;
  X.OBJ[X.N] := Y;
  WRITELN('ELEMENTO ADICIONADO');
END;

FUNCTION Q(X: PILHA): INTEGER;
BEGIN
  Q := X.N;
END;

VAR
  P: PILHA;
  I, QTDE: INTEGER;
  ELEMENTO: STRING;

BEGIN

  INIT(P);
  REPEAT
    WRITELN('ADICIONE OS ELEMENTOS NA PILHA: ');
    READLN(ELEMENTO);
    PUSH(P, ELEMENTO);
    WRITELN('DIGITE');
    WRITELN('1 PARA ADICIONAR OUTRO ELEMENTO');
    WRITELN('2 PARA VERIFICAR QUANTOS ELEMENTOS TEM NA PILHA');
    READLN(I);
    IF I = 2 THEN
    BEGIN
      QTDE := Q(P);
      WRITELN('NA PILHA POSSUEM ', QTDE, ' ELEMENTOS');
    END;
  UNTIL (I > 1);

END.